inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'app/assets/**/*'
    - 'db/cable_schema.rb'
    - 'db/cache_schema.rb'
    - 'db/queue_schema.rb'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false
