x-db-config: &db-config
  MYSQL_ROOT_PASSWORD: secret

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      <<: *db-config
    depends_on:
      - db

  db:
    image: mysql:9.2.0-oraclelinux9
    volumes:
      - db-data:/var/lib/mysql
    environment:
      <<: *db-config

volumes:
  db-data:
